import Image from "next/image";

import ReactFormatter from "../../../../components/Formatter/ReactFormatter";
import ShellFormatter from "../../../../components/Formatter/ShellFormatter";
import Chapter from "../../../../components/Course/Chapter";
import { Paragraph } from "../../../../components/Text/Text";
import { reactCourse } from "..";
import Link from "next/link";

const PreparingAStarterProject = () => {
  return (
    <Chapter course={reactCourse}>
      <Paragraph>
        In order to keep us on the same page in every chapter, this chapter
        specifies what our project would look like at the beginning of each
        chapter (unless otherwise specified). This starter project of our course
        for each chapter is created by deleting extra code in the starter
        project generated by create-react-app.
      </Paragraph>
      <Paragraph>
        First of all, use{" "}
        <Link href="/courses/react/introduction/introduction#create-react-app">
          create-react-app
        </Link>{" "}
        to generate a starter project.
      </Paragraph>
      <ShellFormatter>{`$ npx create-react-app your-app-name
$ cd your-app-name
$ npm start # spin up the local server for your react application`}</ShellFormatter>
      <Paragraph>
        Delete all the files other than those which are shown in the screenshot
        below.
      </Paragraph>
      <Image
        src="/images/courses/react/preparing-a-starter-project/starter-project-structure.png"
        alt="The folder structure of the starter project"
        height="334"
        width="232"
      />
      <Paragraph>
        Replace the content of public/index.html by the following.
      </Paragraph>
      <ReactFormatter>{`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>React App</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`}</ReactFormatter>
      <Paragraph>Replace the content of src/App.js by the following.</Paragraph>
      <ReactFormatter>{`function App() {
   return (
     <div>
     </div>
   );
 }
  
 export default App;`}</ReactFormatter>
      <Paragraph>
        Replace the content of src/index.js by the following.
      </Paragraph>
      <ReactFormatter>{`import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
 
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);`}</ReactFormatter>
      <Paragraph>
        Last but not least, delete all the content in src/index.css.
      </Paragraph>
      <Paragraph>
        Congratulations! You now have a brand new React project to start playing
        with, let’s get started on learning some real React in the next chapter!
      </Paragraph>
    </Chapter>
  );
};

export default PreparingAStarterProject;
